<template>
  <tech-frame v-bind="frameInitOptions">
    <div class="title">车组配属信息</div>
    <div class="station-container-div">
      <template v-for="(station, i) in stations">
        <tech-frame v-bind="stationButtonOptions" :fillColor="i === selectedBtn ? 'rgba(255, 0, 0, 0.2)': '#182134'">
          <div class="station-btn-div" @click="switchStationData(i)" >
            <span style="color: #66b3b3">[ </span>{{station}}<span style="color: #66b3b3"> ]</span>
          </div>
        </tech-frame>
      </template>
    </div>
    <echarts-force :raw-data="rawData"></echarts-force>
  </tech-frame>
</template>

<script>
  import TechFrame from '../base/TechFrame'
  import EchartsBar from '../echarts/EchartsSunburst'
  import EchartsForce from '../echarts/EchartsForce'



  export default {
    name: "TrainAllocation",
    components: {EchartsForce, EchartsBar, TechFrame},
    data: function () {
      return {
        stationButtonOptions: {
          size: {width: 150, height: 40},
          blurDistance: 2,
          connerClip: [3, 0, 15, 0],
          fillColor: "#182134"
        },
        stations: [
          '南京南服务站', '合肥南服务站', '杭州服务站',
          '虹桥服务站', '北京服务站', '天津服务站',
          '广州服务站', '深圳服务站', '长沙服务站',
          '西安服务站', '成都服务站', '重庆服务站',
          'X1服务站', 'X2服务站'
        ],
        rawData: [],
        separatedByStation: [],
        selectedBtn: 0
      }
    },
    props: {
      frameInitOptions: {
        type: Object,
        default: () => {
          return {
            size: {width: 7 * 150, height: 150 * 4},
            blurDistance: 3,
            connerClip: [0, 0,  0, 0]
          }
        }
      }
    },
    methods: {
      switchStationData (index) {
        this.rawData = this.separatedByStation[index].trains;
        this.selectedBtn = index;
      },
      separateStation (data) {
        if(data){
          let station = [], result;

          result = data.reduce((p, c, i)=>{

            let stationIdx = station.indexOf(c.station);
            //找到服务站
            if(stationIdx > -1){
              let curStation = p[stationIdx];
              curStation.trains.push(c);

            }else{ //找不到服务站

              station.push(c.station);
              let newStation = {name: c.station};
              newStation.trains = [c];
              p.push(newStation);

            }
            return p;
          }, []);

          this.stations = station;

          return result;
        }

        this.stations = [];
        return null;
      }
    },
    created () {

      let allcar = [
        {"station":"南京南服务站","model":"CRH380BL","train":"3786"},
        {"station":"成都服务站","model":"CRH3A","train":"3108"},
        {"station":"重庆服务站","model":"CRH3C","train":"3002"},
        {"station":"重庆服务站","model":"CRH3C","train":"3009"},
        {"station":"重庆服务站","model":"CRH3C","train":"3015"},
        {"station":"北京服务站","model":"CRH3C","train":"3016"},
        {"station":"重庆服务站","model":"CRH3C","train":"3018"},
        {"station":"长沙服务站","model":"CRH3C","train":"3024"},
        {"station":"深圳服务站","model":"CRH3C","train":"3025"},
        {"station":"长沙服务站","model":"CRH3C","train":"3031"},
        {"station":"深圳服务站","model":"CRH3C","train":"3032"},
        {"station":"长沙服务站","model":"CRH3C","train":"3035"},
        {"station":"深圳服务站","model":"CRH3C","train":"3038"},
        {"station":"深圳服务站","model":"CRH3C","train":"3045"},
        {"station":"深圳服务站","model":"CRH3C","train":"3046"},
        {"station":"长沙服务站","model":"CRH3C","train":"3070"},
        {"station":"深圳服务站","model":"CRH3C","train":"3080"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3501"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3505"},
        {"station":"南京南服务站","model":"CRH380BL","train":"3510"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3516"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3531"},
        {"station":"北京服务站","model":"CRH380B","train":"3691"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3718"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3738"},
        {"station":"西安服务站","model":"CRH380B","train":"3743"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3752"},
        {"station":"西安服务站","model":"CRH380B","train":"3754"},
        {"station":"西安服务站","model":"CRH380B","train":"3762"},
        {"station":"西安服务站","model":"CRH380B","train":"3766"},
        {"station":"西安服务站","model":"CRH380B","train":"3770"},
        {"station":"西安服务站","model":"CRH380B","train":"3774"},
        {"station":"广州服务站","model":"CRH380B","train":"3686"},
        {"station":"长沙服务站","model":"CRH380B","train":"3687"},
        {"station":"西安服务站","model":"CRH380B","train":"3711"},
        {"station":"长沙服务站","model":"CRH380B","train":"3675"},
        {"station":"成都服务站","model":"CR400BF-A","train":"3027BF"},
        {"station":"南京南服务站","model":"CRH380BL","train":"3554"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3557"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3560"},
        {"station":"广州服务站","model":"CRH380B","train":"3577"},
        {"station":"长沙服务站","model":"CRH380B","train":"3584"},
        {"station":"广州服务站","model":"CRH380B","train":"3596"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3609"},
        {"station":"南京南服务站","model":"CRH380B","train":"3616"},
        {"station":"广州服务站","model":"CRH380B","train":"3625"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3641"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3643"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3775"},
        {"station":"深圳服务站","model":"CRH3C","train":"3048"},
        {"station":"长沙服务站","model":"CRH380B","train":"3632"},
        {"station":"长沙服务站","model":"CRH3C","train":"3049"},
        {"station":"长沙服务站","model":"CRH380B","train":"3636"},
        {"station":"长沙服务站","model":"CRH380B","train":"3637"},
        {"station":"长沙服务站","model":"CRH3C","train":"3051"},
        {"station":"长沙服务站","model":"CRH380B","train":"3647"},
        {"station":"深圳服务站","model":"CRH3C","train":"3053"},
        {"station":"广州服务站","model":"CRH380B","train":"3656"},
        {"station":"深圳服务站","model":"CRH3C","train":"3055"},
        {"station":"广州服务站","model":"CRH380B","train":"3657"},
        {"station":"深圳服务站","model":"CRH3C","train":"3057"},
        {"station":"广州服务站","model":"CRH380B","train":"3659"},
        {"station":"长沙服务站","model":"CRH380B","train":"3660"},
        {"station":"长沙服务站","model":"CRH3C","train":"3067"},
        {"station":"广州服务站","model":"CRH380B","train":"3746"},
        {"station":"广州服务站","model":"CRH380B","train":"3747"},
        {"station":"广州服务站","model":"CRH380B","train":"3748"},
        {"station":"南京南服务站","model":"CR400BF","train":"3007BF"},
        {"station":"长沙服务站","model":"CRH380B","train":"3617"},
        {"station":"长沙服务站","model":"CRH380B","train":"3627"},
        {"station":"长沙服务站","model":"CRH380B","train":"3630"},
        {"station":"长沙服务站","model":"CRH380B","train":"3631"},
        {"station":"长沙服务站","model":"CRH380B","train":"3638"},
        {"station":"长沙服务站","model":"CRH380B","train":"3646"},
        {"station":"广州服务站","model":"CRH380B","train":"3651"},
        {"station":"广州服务站","model":"CRH380B","train":"3749"},
        {"station":"天津服务站","model":"CRH380B","train":"3679"},
        {"station":"南京南服务站","model":"CR400BF","train":"3017BF"},
        {"station":"南京南服务站","model":"CR400BF","train":"3021BF"},
        {"station":"成都服务站","model":"CRH3A","train":"3086"},
        {"station":"成都服务站","model":"CRH3A","train":"3092"},
        {"station":"成都服务站","model":"CRH3A","train":"3102"},
        {"station":"南京南服务站","model":"CR400BF","train":"3010BF"},
        {"station":"南京南服务站","model":"CR400BF","train":"3019BF"},
        {"station":"西安服务站","model":"CRH3A","train":"3101"},
        {"station":"西安服务站","model":"CRH3A","train":"3104"},
        {"station":"成都服务站","model":"CRH3A","train":"3089"},
        {"station":"南京南服务站","model":"CR400BF","train":"3011BF"},
        {"station":"南京南服务站","model":"CR400BF","train":"3012BF"},
        {"station":"南京南服务站","model":"CR400BF","train":"3015BF"},
        {"station":"南京南服务站","model":"CR400BF","train":"3018BF"},
        {"station":"南京南服务站","model":"CR400BF","train":"3020BF"},
        {"station":"南京南服务站","model":"CR400BF","train":"3022BF"},
        {"station":"南京南服务站","model":"CR400BF","train":"3023BF"},
        {"station":"西安服务站","model":"CRH3A","train":"3094"},
        {"station":"西安服务站","model":"CRH3A","train":"3096"},
        {"station":"西安服务站","model":"CRH3A","train":"3098"},
        {"station":"成都服务站","model":"CRH3A","train":"3084"},
        {"station":"成都服务站","model":"CRH3A","train":"3099"},
        {"station":"成都服务站","model":"CRH3A","train":"3105"},
        {"station":"成都服务站","model":"CRH3A","train":"3106"},
        {"station":"成都服务站","model":"CRH3A","train":"3107"},
        {"station":"成都服务站","model":"CRH3A","train":"3081"},
        {"station":"南京南服务站","model":"CRH380BL","train":"3784"},
        {"station":"成都服务站","model":"CRH3A","train":"3090"},
        {"station":"成都服务站","model":"CRH3A","train":"3093"},
        {"station":"成都服务站","model":"CRH3A","train":"3095"},
        {"station":"成都服务站","model":"CRH3A","train":"3097"},
        {"station":"成都服务站","model":"CRH3A","train":"3100"},
        {"station":"成都服务站","model":"CRH3A","train":"3110"},
        {"station":"成都服务站","model":"CRH3A","train":"3111"},
        {"station":"北京服务站","model":"CR400BF","train":"0305BF"},
        {"station":"南京南服务站","model":"CR400BF","train":"3016BF"},
        {"station":"南京南服务站","model":"CR400BF","train":"3013BF"},
        {"station":"南京南服务站","model":"CR400BF","train":"3014BF"},
        {"station":"西安服务站","model":"CRH3A","train":"3103"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3776"},
        {"station":"长沙服务站","model":"CRH380B","train":"3610"},
        {"station":"长沙服务站","model":"CRH3C","train":"3061"},
        {"station":"长沙服务站","model":"CRH3C","train":"3069"},
        {"station":"长沙服务站","model":"CRH3C","train":"3077"},
        {"station":"长沙服务站","model":"CRH3C","train":"3079"},
        {"station":"长沙服务站","model":"CRH380B","train":"3680"},
        {"station":"长沙服务站","model":"CRH380B","train":"3684"},
        {"station":"广州服务站","model":"CRH380B","train":"3689"},
        {"station":"北京服务站","model":"CRH380B","train":"3690"},
        {"station":"长沙服务站","model":"CRH380B","train":"3699"},
        {"station":"广州服务站","model":"CRH380B","train":"3708"},
        {"station":"西安服务站","model":"CRH380B","train":"3726"},
        {"station":"成都服务站","model":"CRH3A","train":"3082"},
        {"station":"成都服务站","model":"CRH3A","train":"3083"},
        {"station":"成都服务站","model":"CRH3A","train":"3085"},
        {"station":"成都服务站","model":"CRH3A","train":"3087"},
        {"station":"成都服务站","model":"CRH3A","train":"3088"},
        {"station":"成都服务站","model":"CRH3A","train":"3091"},
        {"station":"成都服务站","model":"CRH3A","train":"3109"},
        {"station":"北京服务站","model":"CRH380B","train":"3696"},
        {"station":"天津服务站","model":"CRH380B","train":"3697"},
        {"station":"天津服务站","model":"CRH380B","train":"3702"},
        {"station":"天津服务站","model":"CRH380B","train":"3703"},
        {"station":"西安服务站","model":"CRH380B","train":"3709"},
        {"station":"西安服务站","model":"CRH380B","train":"3731"},
        {"station":"西安服务站","model":"CRH380B","train":"3742"},
        {"station":"西安服务站","model":"CRH380B","train":"3744"},
        {"station":"西安服务站","model":"CRH380B","train":"3750"},
        {"station":"西安服务站","model":"CRH380B","train":"3755"},
        {"station":"西安服务站","model":"CRH380B","train":"3756"},
        {"station":"西安服务站","model":"CRH380B","train":"3757"},
        {"station":"西安服务站","model":"CRH380B","train":"3758"},
        {"station":"西安服务站","model":"CRH380B","train":"3759"},
        {"station":"西安服务站","model":"CRH380B","train":"3760"},
        {"station":"西安服务站","model":"CRH380B","train":"3761"},
        {"station":"西安服务站","model":"CRH380B","train":"3763"},
        {"station":"西安服务站","model":"CRH380B","train":"3764"},
        {"station":"西安服务站","model":"CRH380B","train":"3765"},
        {"station":"西安服务站","model":"CRH380B","train":"3767"},
        {"station":"西安服务站","model":"CRH380B","train":"3768"},
        {"station":"西安服务站","model":"CRH380B","train":"3769"},
        {"station":"西安服务站","model":"CRH380B","train":"3771"},
        {"station":"西安服务站","model":"CRH380B","train":"3772"},
        {"station":"西安服务站","model":"CRH380B","train":"3773"},
        {"station":"南京南服务站","model":"CRH380BL","train":"3777"},
        {"station":"南京南服务站","model":"CRH380BL","train":"3778"},
        {"station":"南京南服务站","model":"CRH380BL","train":"3779"},
        {"station":"长沙服务站","model":"CRH380B","train":"3650"},
        {"station":"深圳服务站","model":"CRH3C","train":"3056"},
        {"station":"长沙服务站","model":"CRH380B","train":"3658"},
        {"station":"长沙服务站","model":"CRH380B","train":"3685"},
        {"station":"广州服务站","model":"CRH380B","train":"3688"},
        {"station":"广州服务站","model":"CRH380B","train":"3700"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3753"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3741"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3736"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3727"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3719"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3715"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3671"},
        {"station":"天津服务站","model":"CRH380B","train":"3662"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3704"},
        {"station":"长沙服务站","model":"CRH3C","train":"3033"},
        {"station":"南京南服务站","model":"CRH380BL","train":"3523"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3541"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3580"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3655"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3581"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3635"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3654"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3720"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3585"},
        {"station":"南京南服务站","model":"CRH380BL","train":"3556"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3534"},
        {"station":"北京服务站","model":"CRH3C","train":"3019"},
        {"station":"广州服务站","model":"CRH380B","train":"3578"},
        {"station":"长沙服务站","model":"CRH3C","train":"3034"},
        {"station":"深圳服务站","model":"CRH3C","train":"3074"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3517"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3542"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3571"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3604"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3677"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3507"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3533"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3678"},
        {"station":"北京服务站","model":"CRH380B","train":"3667"},
        {"station":"西安服务站","model":"CRH380B","train":"3706"},
        {"station":"长沙服务站","model":"CRH380B","train":"3698"},
        {"station":"天津服务站","model":"CRH380B","train":"3692"},
        {"station":"长沙服务站","model":"CRH3C","train":"3041"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3547"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3576"},
        {"station":"南京南服务站","model":"CRH380B","train":"3614"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3512"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3652"},
        {"station":"长沙服务站","model":"CRH380B","train":"3681"},
        {"station":"广州服务站","model":"CRH380B","train":"3621"},
        {"station":"长沙服务站","model":"CRH3C","train":"3054"},
        {"station":"深圳服务站","model":"CRH3C","train":"3071"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3519"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3527"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3538"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3544"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3552"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3561"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3564"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3567"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3570"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3573"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3588"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3591"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3598"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3602"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3605"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3608"},
        {"station":"南京南服务站","model":"CRH380B","train":"3620"},
        {"station":"南京南服务站","model":"CRH380B","train":"3645"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3664"},
        {"station":"南京南服务站","model":"CRH380BL","train":"3550"},
        {"station":"南京南服务站","model":"CRH380B","train":"3594"},
        {"station":"南京南服务站","model":"CRH380B","train":"3615"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3515"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3524"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3530"},
        {"station":"南京南服务站","model":"CRH380B","train":"3613"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3624"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3634"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3640"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3682"},
        {"station":"重庆服务站","model":"CRH3C","train":"3001"},
        {"station":"北京服务站","model":"CRH3C","train":"3004"},
        {"station":"北京服务站","model":"CRH3C","train":"3007"},
        {"station":"北京服务站","model":"CRH3C","train":"3010"},
        {"station":"北京服务站","model":"CRH3C","train":"3012"},
        {"station":"长沙服务站","model":"CRH380B","train":"3661"},
        {"station":"北京服务站","model":"CRH380B","train":"3668"},
        {"station":"北京服务站","model":"CRH380B","train":"3695"},
        {"station":"长沙服务站","model":"CRH3C","train":"3050"},
        {"station":"长沙服务站","model":"CRH380B","train":"3582"},
        {"station":"长沙服务站","model":"CRH380B","train":"3622"},
        {"station":"长沙服务站","model":"CRH3C","train":"3058"},
        {"station":"长沙服务站","model":"CRH3C","train":"3068"},
        {"station":"长沙服务站","model":"CRH3C","train":"3078"},
        {"station":"长沙服务站","model":"CRH3C","train":"3042"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3518"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3536"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3545"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3558"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3566"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3574"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3589"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3603"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3611"},
        {"station":"南京南服务站","model":"CRH380B","train":"3649"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3672"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3705"},
        {"station":"南京南服务站","model":"CRH380B","train":"3717"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3728"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3735"},
        {"station":"西安服务站","model":"CRH380B","train":"3740"},
        {"station":"南京南服务站","model":"CRH380BL","train":"3559"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3503"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3511"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3529"},
        {"station":"北京服务站","model":"CRH380B","train":"3669"},
        {"station":"南京南服务站","model":"CRH380B","train":"3644"},
        {"station":"长沙服务站","model":"CRH3C","train":"3052"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3600"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3676"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3730"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3721"},
        {"station":"南京南服务站","model":"CRH380BL","train":"3785"},
        {"station":"广州服务站","model":"CRH380B","train":"3648"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3508"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3540"},
        {"station":"南京南服务站","model":"CRH380BL","train":"3780"},
        {"station":"长沙服务站","model":"CRH3C","train":"3064"},
        {"station":"长沙服务站","model":"CRH3C","train":"3066"},
        {"station":"深圳服务站","model":"CRH3C","train":"3072"},
        {"station":"深圳服务站","model":"CRH3C","train":"3075"},
        {"station":"深圳服务站","model":"CRH3C","train":"3076"},
        {"station":"广州服务站","model":"CRH380B","train":"3701"},
        {"station":"广州服务站","model":"CRH380B","train":"3707"},
        {"station":"西安服务站","model":"CRH380B","train":"3710"},
        {"station":"广州服务站","model":"CRH380B","train":"3725"},
        {"station":"长沙服务站","model":"CRH3C","train":"3030"},
        {"station":"南京南服务站","model":"CRH380BL","train":"3781"},
        {"station":"南京南服务站","model":"CRH380BL","train":"3782"},
        {"station":"南京南服务站","model":"CRH380BL","train":"3783"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3623"},
        {"station":"深圳服务站","model":"CRH3C","train":"3023"},
        {"station":"长沙服务站","model":"CRH3C","train":"3040"},
        {"station":"广州服务站","model":"CRH380BL","train":"3525"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3553"},
        {"station":"南京南服务站","model":"CRH380B","train":"3572"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3590"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3663"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3673"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3729"},
        {"station":"南京南服务站","model":"CRH380BL","train":"3548"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3506"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3528"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3629"},
        {"station":"北京服务站","model":"CRH3C","train":"3006"},
        {"station":"北京服务站","model":"CRH3C","train":"3020"},
        {"station":"北京服务站","model":"CRH3C","train":"3008"},
        {"station":"南京南服务站","model":"CR400BF","train":"3001BF"},
        {"station":"北京服务站","model":"CR400BF-A","train":"3024BF"},
        {"station":"北京服务站","model":"CR400BF-A","train":"3025BF"},
        {"station":"南京南服务站","model":"CR400BF","train":"3002BF"},
        {"station":"南京南服务站","model":"CR400BF","train":"3003BF"},
        {"station":"南京南服务站","model":"CR400BF","train":"3004BF"},
        {"station":"南京南服务站","model":"CR400BF","train":"3005BF"},
        {"station":"南京南服务站","model":"CR400BF","train":"3006BF"},
        {"station":"南京南服务站","model":"CR400BF","train":"3008BF"},
        {"station":"南京南服务站","model":"CR400BF","train":"3009BF"},
        {"station":"长沙服务站","model":"CRH3C","train":"3026"},
        {"station":"深圳服务站","model":"CRH3C","train":"3043"},
        {"station":"长沙服务站","model":"CRH3C","train":"3060"},
        {"station":"广州服务站","model":"CRH380B","train":"3599"},
        {"station":"长沙服务站","model":"CRH380B","train":"3628"},
        {"station":"长沙服务站","model":"CRH3C","train":"3017"},
        {"station":"深圳服务站","model":"CRH3C","train":"3022"},
        {"station":"长沙服务站","model":"CRH3C","train":"3028"},
        {"station":"长沙服务站","model":"CRH3C","train":"3044"},
        {"station":"深圳服务站","model":"CRH3C","train":"3059"},
        {"station":"长沙服务站","model":"CRH3C","train":"3062"},
        {"station":"长沙服务站","model":"CRH3C","train":"3063"},
        {"station":"长沙服务站","model":"CRH3C","train":"3065"},
        {"station":"深圳服务站","model":"CRH3C","train":"3073"},
        {"station":"长沙服务站","model":"CRH380B","train":"3597"},
        {"station":"长沙服务站","model":"CRH3C","train":"3027"},
        {"station":"深圳服务站","model":"CRH3C","train":"3029"},
        {"station":"长沙服务站","model":"CRH3C","train":"3036"},
        {"station":"长沙服务站","model":"CRH3C","train":"3037"},
        {"station":"长沙服务站","model":"CRH3C","train":"3039"},
        {"station":"长沙服务站","model":"CRH3C","train":"3047"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3502"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3520"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3522"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3526"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3539"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3543"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3546"},
        {"station":"南京南服务站","model":"CRH380BL","train":"3549"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3555"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3562"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3563"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3565"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3568"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3569"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3575"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3579"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3583"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3586"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3587"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3592"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3601"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3606"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3607"},
        {"station":"南京南服务站","model":"CRH380B","train":"3618"},
        {"station":"南京南服务站","model":"CRH380B","train":"3633"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3665"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3666"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3712"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3713"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3714"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3716"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3722"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3723"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3724"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3732"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3733"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3734"},
        {"station":"虹桥服务站","model":"CRH380BL","train":"3737"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3739"},
        {"station":"虹桥服务站","model":"CRH380B","train":"3745"},
        {"station":"西安服务站","model":"CRH380B","train":"3751"},
        {"station":"南京南服务站","model":"CRH380BL","train":"3551"},
        {"station":"南京南服务站","model":"CRH380B","train":"3595"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3612"},
        {"station":"南京南服务站","model":"CRH380B","train":"3642"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3504"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3509"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3513"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3514"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3521"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3532"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3535"},
        {"station":"杭州服务站","model":"CRH380BL","train":"3537"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3593"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3619"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3626"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3639"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3653"},
        {"station":"合肥南服务站","model":"CRH380B","train":"3674"},
        {"station":"北京服务站","model":"CRH3C","train":"3003"},
        {"station":"北京服务站","model":"CRH3C","train":"3005"},
        {"station":"北京服务站","model":"CRH3C","train":"3011"},
        {"station":"北京服务站","model":"CRH3C","train":"3013"},
        {"station":"北京服务站","model":"CRH3C","train":"3014"},
        {"station":"北京服务站","model":"CRH3C","train":"3021"},
        {"station":"北京服务站","model":"CRH380B","train":"3670"},
        {"station":"长沙服务站","model":"CRH380B","train":"3683"},
        {"station":"天津服务站","model":"CRH380B","train":"3693"},
        {"station":"北京服务站","model":"CRH380B","train":"3694"}
      ];

      this.separatedByStation = this.separateStation(allcar);
      this.rawData = this.separatedByStation[0].trains;

    }
  }
</script>

<style scoped>
  .title {
    height: 40px;
    font-size: 25px;
  }

  .station-container-div {
    width: 180px;
    display: inline-block;
    float: left;
    text-align: left;

    padding-left: 40px;
  }

  .station-btn-div {
    cursor: pointer;

  }
</style>
